# Indexing : Accessing Single Elements


Python’s standard list indexing, indexing in NumPy will feel
quite familiar.

##  one-dimensional array
You can access the ith value (counting from
zero) by specifying the desired index in square brackets, just as with Python lists:

> **`syntax : array[index]`**-- **for single item**

##### Multi Indexing
It means passing an array of indices to access multiple array elements at once.

> **`syntax : array[[index,index..]]`** -- **for multiple items based on index**

In [1]:
import numpy as np

In [2]:
arr = np.array([2,3,6,7,8,9,1])

In [3]:
arr[2] # value at index 2

6

In [ ]:
arr[[2,5,4]] # To access multiple elements send a list of index numbers


In [ ]:
arr[[2,1,5,6]]

## Multi-dimensional array

In a multidimensional array, you access items using a comma-separated tuple of
indices:

**`syntax : array[row ,column]`**

In [6]:
arr2 = np.arange(10)

In [7]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr2 = arr2.reshape(2,5)

In [9]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
arr2[0][0]

0

In [11]:
arr2[0][1]

1

In [12]:
arr2[0,1]

1

In [13]:
arr2[1,2]

7

In [14]:
arr2[1,4]

9

In [15]:
arr3 =  np.arange(9)

In [18]:
arr3 = arr3.reshape((9,1))

In [19]:
arr3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [20]:
arr3[4,0]

4

In [ ]:
arr3[2,2]

In [ ]:
arr3

In [ ]:
arr3[1,2]

In [ ]:
arr3[2,1]

#### 3D -Indexing


In [ ]:
l  = [[[2, 3, 6, 7], [4, 7, 8, 9], [7, 8, 9, 6]]]

In [ ]:
arr_3d = np.array(l)

In [ ]:
arr_3d

In [ ]:
arr_3d[0]

In [ ]:
arr_3d[0][0]

In [ ]:
arr_3d[0][0][0]

In [ ]:
arr_3d[0][1][0]

In [ ]:
arr_3d[0,1:3,1:3]

# Slicing : Accessing sub-arrays

Access subarrays with the slice notation, marked by the colon (:) character.

To access a slice of an array x, use this: **`x[start:stop:step]`**

## one dimensional subarrays 

In [21]:
x = np.array([5,7,8,9,3,5,1])

In [22]:
x

array([5, 7, 8, 9, 3, 5, 1])

In [23]:
# All elements
x[:]

array([5, 7, 8, 9, 3, 5, 1])

In [24]:
# first five elements
x[:5]

array([5, 7, 8, 9, 3])

In [25]:
# elements after 2nd index
x[2:]

array([8, 9, 3, 5, 1])

In [26]:
# sub-array from 2 to 5(exclusive)
x[2:5]

array([8, 9, 3])

In [27]:
x

array([5, 7, 8, 9, 3, 5, 1])

In [29]:
x = np.array([5,7,8,9,3,5,1])

In [30]:
x

array([5, 7, 8, 9, 3, 5, 1])

In [28]:
# every 2nd or other element
x[ 0: : 2]

array([5, 8, 3, 1])

In [31]:
# every 2nd or other element
x[ 0: : 3]

array([5, 9, 1])

In [32]:
# every other element starting from 1
x[ 1: : 2]

array([7, 9, 5])

## Multidimensional sub-arrays

Multidimensional slices work in the same way, with multiple slices separated by commas.

**`x[ row_start:row_end:step  , col_start :col_end:step]`**

In [33]:
x = np.random.rand(5,5)

In [34]:
x

array([[0.54652797, 0.40633134, 0.77859621, 0.94861105, 0.28138964],
       [0.02150031, 0.91878831, 0.9862544 , 0.79396185, 0.71702492],
       [0.0196022 , 0.13849138, 0.485424  , 0.81724517, 0.47817375],
       [0.01241748, 0.42321807, 0.51992906, 0.98525609, 0.09036283],
       [0.70274574, 0.41709622, 0.11730024, 0.78219315, 0.33692054]])

In [35]:
x[:,:]

array([[0.54652797, 0.40633134, 0.77859621, 0.94861105, 0.28138964],
       [0.02150031, 0.91878831, 0.9862544 , 0.79396185, 0.71702492],
       [0.0196022 , 0.13849138, 0.485424  , 0.81724517, 0.47817375],
       [0.01241748, 0.42321807, 0.51992906, 0.98525609, 0.09036283],
       [0.70274574, 0.41709622, 0.11730024, 0.78219315, 0.33692054]])

In [36]:
x[1:]

array([[0.02150031, 0.91878831, 0.9862544 , 0.79396185, 0.71702492],
       [0.0196022 , 0.13849138, 0.485424  , 0.81724517, 0.47817375],
       [0.01241748, 0.42321807, 0.51992906, 0.98525609, 0.09036283],
       [0.70274574, 0.41709622, 0.11730024, 0.78219315, 0.33692054]])

In [37]:
x[0: ]

array([[0.54652797, 0.40633134, 0.77859621, 0.94861105, 0.28138964],
       [0.02150031, 0.91878831, 0.9862544 , 0.79396185, 0.71702492],
       [0.0196022 , 0.13849138, 0.485424  , 0.81724517, 0.47817375],
       [0.01241748, 0.42321807, 0.51992906, 0.98525609, 0.09036283],
       [0.70274574, 0.41709622, 0.11730024, 0.78219315, 0.33692054]])

In [38]:
x[:,:3]

array([[0.54652797, 0.40633134, 0.77859621],
       [0.02150031, 0.91878831, 0.9862544 ],
       [0.0196022 , 0.13849138, 0.485424  ],
       [0.01241748, 0.42321807, 0.51992906],
       [0.70274574, 0.41709622, 0.11730024]])

In [39]:
x[ :, 0:2]

array([[0.54652797, 0.40633134],
       [0.02150031, 0.91878831],
       [0.0196022 , 0.13849138],
       [0.01241748, 0.42321807],
       [0.70274574, 0.41709622]])

In [40]:
x[ 0:2 ,  0:1 ]

array([[0.54652797],
       [0.02150031]])

In [41]:
x[ 1: , 1: ]

array([[0.91878831, 0.9862544 , 0.79396185, 0.71702492],
       [0.13849138, 0.485424  , 0.81724517, 0.47817375],
       [0.42321807, 0.51992906, 0.98525609, 0.09036283],
       [0.41709622, 0.11730024, 0.78219315, 0.33692054]])

In [42]:
x[ 1:]

array([[0.02150031, 0.91878831, 0.9862544 , 0.79396185, 0.71702492],
       [0.0196022 , 0.13849138, 0.485424  , 0.81724517, 0.47817375],
       [0.01241748, 0.42321807, 0.51992906, 0.98525609, 0.09036283],
       [0.70274574, 0.41709622, 0.11730024, 0.78219315, 0.33692054]])

In [43]:
x[ 1:, :2]

array([[0.02150031, 0.91878831],
       [0.0196022 , 0.13849138],
       [0.01241748, 0.42321807],
       [0.70274574, 0.41709622]])

In [44]:
x[ 1:,2:]

array([[0.9862544 , 0.79396185, 0.71702492],
       [0.485424  , 0.81724517, 0.47817375],
       [0.51992906, 0.98525609, 0.09036283],
       [0.11730024, 0.78219315, 0.33692054]])

In [45]:
x

array([[0.54652797, 0.40633134, 0.77859621, 0.94861105, 0.28138964],
       [0.02150031, 0.91878831, 0.9862544 , 0.79396185, 0.71702492],
       [0.0196022 , 0.13849138, 0.485424  , 0.81724517, 0.47817375],
       [0.01241748, 0.42321807, 0.51992906, 0.98525609, 0.09036283],
       [0.70274574, 0.41709622, 0.11730024, 0.78219315, 0.33692054]])

In [46]:
x[ 2:,2:]

array([[0.485424  , 0.81724517, 0.47817375],
       [0.51992906, 0.98525609, 0.09036283],
       [0.11730024, 0.78219315, 0.33692054]])

In [47]:
x[2:,1:3]

array([[0.13849138, 0.485424  ],
       [0.42321807, 0.51992906],
       [0.41709622, 0.11730024]])

In [48]:
x[2:, : 1]

array([[0.0196022 ],
       [0.01241748],
       [0.70274574]])

In [58]:
x

array([[0.54652797, 0.40633134, 0.77859621, 0.94861105, 0.28138964],
       [0.02150031, 0.91878831, 0.9862544 , 0.79396185, 0.71702492],
       [0.0196022 , 0.13849138, 0.485424  , 0.81724517, 0.47817375],
       [0.01241748, 0.42321807, 0.51992906, 0.98525609, 0.09036283],
       [0.70274574, 0.41709622, 0.11730024, 0.78219315, 0.33692054]])

In [61]:
x[ :, 0 : 2]

array([[0.54652797, 0.40633134],
       [0.02150031, 0.91878831],
       [0.0196022 , 0.13849138],
       [0.01241748, 0.42321807],
       [0.70274574, 0.41709622]])

In [60]:
x[,0:2]

SyntaxError: invalid syntax (<ipython-input-60-dcddbffb31fc>, line 1)

In [49]:
x[ : 2]

array([[0.54652797, 0.40633134, 0.77859621, 0.94861105, 0.28138964],
       [0.02150031, 0.91878831, 0.9862544 , 0.79396185, 0.71702492]])

In [50]:
x[ 1:2 , 1:2]

array([[0.91878831]])

In [51]:
x

array([[0.54652797, 0.40633134, 0.77859621, 0.94861105, 0.28138964],
       [0.02150031, 0.91878831, 0.9862544 , 0.79396185, 0.71702492],
       [0.0196022 , 0.13849138, 0.485424  , 0.81724517, 0.47817375],
       [0.01241748, 0.42321807, 0.51992906, 0.98525609, 0.09036283],
       [0.70274574, 0.41709622, 0.11730024, 0.78219315, 0.33692054]])

In [52]:
x[1:2,2:3]

array([[0.9862544]])

In [53]:
x

array([[0.54652797, 0.40633134, 0.77859621, 0.94861105, 0.28138964],
       [0.02150031, 0.91878831, 0.9862544 , 0.79396185, 0.71702492],
       [0.0196022 , 0.13849138, 0.485424  , 0.81724517, 0.47817375],
       [0.01241748, 0.42321807, 0.51992906, 0.98525609, 0.09036283],
       [0.70274574, 0.41709622, 0.11730024, 0.78219315, 0.33692054]])

In [54]:
x[ ::2,::2 ]

array([[0.54652797, 0.77859621, 0.28138964],
       [0.0196022 , 0.485424  , 0.47817375],
       [0.70274574, 0.11730024, 0.33692054]])

In [55]:
x[ ::1, ::1]

array([[0.54652797, 0.40633134, 0.77859621, 0.94861105, 0.28138964],
       [0.02150031, 0.91878831, 0.9862544 , 0.79396185, 0.71702492],
       [0.0196022 , 0.13849138, 0.485424  , 0.81724517, 0.47817375],
       [0.01241748, 0.42321807, 0.51992906, 0.98525609, 0.09036283],
       [0.70274574, 0.41709622, 0.11730024, 0.78219315, 0.33692054]])

In [56]:
x[ : ]

array([[0.54652797, 0.40633134, 0.77859621, 0.94861105, 0.28138964],
       [0.02150031, 0.91878831, 0.9862544 , 0.79396185, 0.71702492],
       [0.0196022 , 0.13849138, 0.485424  , 0.81724517, 0.47817375],
       [0.01241748, 0.42321807, 0.51992906, 0.98525609, 0.09036283],
       [0.70274574, 0.41709622, 0.11730024, 0.78219315, 0.33692054]])

In [57]:
x[ 2:3 ]

array([[0.0196022 , 0.13849138, 0.485424  , 0.81724517, 0.47817375]])

In [62]:
x[ 2:3, 1:2 ]

array([[0.13849138]])