### Numpy(Numerical Python)

Related to creating a matrix, slicing concept, operations.

In [1]:
# import numpy library
import numpy as np

In [153]:
d=[67,78,89,23,34,45]

In [3]:
# shape method
d.shape

AttributeError: 'list' object has no attribute 'shape'

In [4]:
# array function
np.array(d)  # single dimensional array

array([67, 78, 89, 23, 34, 45])

In [5]:
np.array(d).shape   # (Rows,columns)

(6,)

In [6]:
np.array(d).reshape(2,3)    # (Rows*columns)=number of values

array([[67, 78, 89],
       [23, 34, 45]])

In [7]:
np.array(d).reshape(3,2) 

array([[67, 78],
       [89, 23],
       [34, 45]])

In [8]:
np.array(d).reshape(6,1) 

array([[67],
       [78],
       [89],
       [23],
       [34],
       [45]])

In [9]:
np.array(d).reshape(1,6) 

array([[67, 78, 89, 23, 34, 45]])

In [11]:
d=np.array([[5,15,20],[25,30,35],[40,45,50]])

In [12]:
d.shape

(3, 3)

In [13]:
d.reshape(9,1)

array([[ 5],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45],
       [50]])

In [14]:
d.reshape(1,9)

array([[ 5, 15, 20, 25, 30, 35, 40, 45, 50]])

In [ ]:
# arange function,
# Returns equally spaced values within the specified interval
# Bydefault equal spacing is 1
# syntax is np.arange(start,endpoint,steps)   endpoint is n-1

In [15]:
np.arange(4,20)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(4,20,1)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(4,30,3)

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28])

In [22]:
np.arange(8,40,5)

array([ 8, 13, 18, 23, 28, 33, 38])

In [23]:
np.arange(8,40,5).shape

(7,)

In [20]:
np.arange(7,40,5).reshape(7,1)

array([[ 7],
       [12],
       [17],
       [22],
       [27],
       [32],
       [37]])

In [21]:
np.arange(7,40,5).reshape(1,7)  # (Rows,columns)

array([[ 7, 12, 17, 22, 27, 32, 37]])

In [24]:
# Random function
# rand function, uniform distribution, ranges from 0 to 1
# randn function, standard normal distribution, ranges -3 to +3
# randint function, interval

In [39]:
# rand function
np.random.rand(3,4)

array([[0.82036359, 0.46409175, 0.42376787, 0.58135052],
       [0.73551519, 0.17083639, 0.91486188, 0.73917961],
       [0.67053653, 0.83061374, 0.57610447, 0.50093935]])

In [49]:
# randn function
np.random.randn(2,3)

array([[ 0.04555188, -0.93747476,  2.12256232],
       [ 1.35125435,  1.66349473,  1.0523598 ]])

In [78]:
# randint function
np.random.randint(8)  # endpoint n-1

3

In [110]:
np.random.randint(-4,30)

26

In [122]:
np.random.randint(-4,30,10)

array([29,  2, -4, 21,  6, 17,  6,  9, 18,  2])

In [141]:
np.random.randint(-4,30,(3,3))

array([[ 0, 11, 28],
       [24, 10,  9],
       [ 9,  2, 10]])

In [149]:
np.array([5,15,20,25,30,35,40,45,50])

array([ 5, 15, 20, 25, 30, 35, 40, 45, 50])

In [142]:
d

array([[ 5, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [144]:
d.min()

5

In [145]:
d.max()

50

In [151]:
# argmin function, to check min value inwhich index position it is
d.argmin()

0

In [148]:
d.argmax()# to check max value in which index position it is

8

In [ ]:
# slicing concept , single dimensional array, multi dimensional array

In [155]:
a=np.array(d)

In [156]:
a

array([67, 78, 89, 23, 34, 45])

In [157]:
# syntax is variablename[indexnumber]

In [158]:
a[0]

67

In [159]:
a[3]

23

In [160]:
a[5]

45

In [162]:
np.where(a==23)   # where function

(array([3]),)

In [170]:
a

array([67, 78, 89, 23, 34, 45])

In [163]:
# multiple values
a[[0,3,5]]  # index

array([67, 23, 45])

In [164]:
a

array([67, 78, 89, 23, 34, 45])

In [169]:
# colon method, continous indexing

In [171]:
a[1:5]   # n-1=4

array([78, 89, 23, 34])

In [167]:
a[1:6]  # n-1=lastindex   n-1=5

array([78, 89, 23, 34, 45])

In [168]:
a[0:4]   # n-1=3

array([67, 78, 89, 23])

In [2]:
# Multi dimensional array
data=np.array([[34,45,6],[56,67,88],[89,90,99]])

In [3]:
data

array([[34, 45,  6],
       [56, 67, 88],
       [89, 90, 99]])

In [5]:
# syntax is variablename[rowindexnumber,columnindexnumber]
data[0,0]

34

In [11]:
data[0:3,1:2]    # n-1=lastindex

array([[45],
       [67],
       [90]])

In [12]:
data

array([[34, 45,  6],
       [56, 67, 88],
       [89, 90, 99]])

In [15]:
data[1:3,2:3]

array([[88],
       [99]])

In [18]:
data[0:1,1:3]

array([[45,  6]])

In [21]:
data[1:3,0:1]

array([[56],
       [89]])

In [24]:
data[1:2,0:3]

array([[56, 67, 88]])

In [25]:
data[1:2]

array([[56, 67, 88]])

In [26]:
data[1:2,0:]

array([[56, 67, 88]])

In [27]:
data[1:2,:3]

array([[56, 67, 88]])

In [28]:
data[1:2,:]

array([[56, 67, 88]])

In [29]:
data

array([[34, 45,  6],
       [56, 67, 88],
       [89, 90, 99]])

In [40]:
data.diagonal()

array([34, 67, 99])

In [43]:
np.fliplr(data).diagonal()

array([ 6, 67, 89])

In [31]:
data[[0,1,2],[0,1,2]]

array([34, 67, 99])

In [35]:
data[0:2,0:2]

array([[34, 45],
       [56, 67]])

In [37]:
data[1:3,2:3]

array([[88],
       [99]])

In [44]:
data

array([[34, 45,  6],
       [56, 67, 88],
       [89, 90, 99]])

In [47]:
b=np.arange(2,20).reshape(2,9)

In [48]:
b

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])