### Numpy(Numerical Python)

Related to creating a matrix, slicing concept, operations.

In [1]:
# import numpy library
import numpy as np

In [2]:
d=[67,78,89,23,34,45]

In [3]:
# shape method
d.shape

AttributeError: 'list' object has no attribute 'shape'

In [4]:
# array function
np.array(d)  # single dimensional array

array([67, 78, 89, 23, 34, 45])

In [5]:
np.array(d).shape   # (Rows,columns)

(6,)

In [6]:
np.array(d).reshape(2,3)    # (Rows*columns)=number of values

array([[67, 78, 89],
       [23, 34, 45]])

In [7]:
np.array(d).reshape(3,2) 

array([[67, 78],
       [89, 23],
       [34, 45]])

In [8]:
np.array(d).reshape(6,1) 

array([[67],
       [78],
       [89],
       [23],
       [34],
       [45]])

In [9]:
np.array(d).reshape(1,6) 

array([[67, 78, 89, 23, 34, 45]])

In [11]:
d=np.array([[5,15,20],[25,30,35],[40,45,50]])

In [12]:
d.shape

(3, 3)

In [13]:
d.reshape(9,1)

array([[ 5],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45],
       [50]])

In [14]:
d.reshape(1,9)

array([[ 5, 15, 20, 25, 30, 35, 40, 45, 50]])

In [ ]:
# arange function,
# Returns equally spaced values within the specified interval
# Bydefault equal spacing is 1
# syntax is np.arange(start,endpoint,steps)   endpoint is n-1

In [15]:
np.arange(4,20)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(4,20,1)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(4,30,3)

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28])

In [22]:
np.arange(8,40,5)

array([ 8, 13, 18, 23, 28, 33, 38])

In [23]:
np.arange(8,40,5).shape

(7,)

In [20]:
np.arange(7,40,5).reshape(7,1)

array([[ 7],
       [12],
       [17],
       [22],
       [27],
       [32],
       [37]])

In [21]:
np.arange(7,40,5).reshape(1,7)  # (Rows,columns)

array([[ 7, 12, 17, 22, 27, 32, 37]])

In [24]:
# Random function
# rand function, uniform distribution, ranges from 0 to 1
# randn function, standard normal distribution, ranges -3 to +3
# randint function, interval

In [39]:
# rand function
np.random.rand(3,4)

array([[0.82036359, 0.46409175, 0.42376787, 0.58135052],
       [0.73551519, 0.17083639, 0.91486188, 0.73917961],
       [0.67053653, 0.83061374, 0.57610447, 0.50093935]])

In [49]:
# randn function
np.random.randn(2,3)

array([[ 0.04555188, -0.93747476,  2.12256232],
       [ 1.35125435,  1.66349473,  1.0523598 ]])

In [17]:
# randint function
np.random.randint(8)  # endpoint n-1

6

In [24]:
np.random.randint(-4,30)

1

In [35]:
np.random.randint(-4,30,10)

array([ 4, 15, 23, 12, -2, 25, 16,  7, 29, 23])

In [41]:
np.random.randint(-4,30,(3,3))

array([[ 6, 22,  5],
       [13,  7, 17],
       [20, 10, 29]])

In [149]:
np.array([5,15,20,25,30,35,40,45,50])

array([ 5, 15, 20, 25, 30, 35, 40, 45, 50])

In [142]:
d

array([[ 5, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [144]:
d.min()

5

In [145]:
d.max()

50

In [151]:
# argmin function, to check min value inwhich index position it is
d.argmin()

0

In [148]:
d.argmax()# to check max value in which index position it is

8

In [ ]:
# slicing concept , single dimensional array, multi dimensional array

In [155]:
a=np.array(d)

In [156]:
a

array([67, 78, 89, 23, 34, 45])

In [157]:
# syntax is variablename[indexnumber]

In [158]:
a[0]

67

In [159]:
a[3]

23

In [160]:
a[5]

45

In [162]:
np.where(a==23)   # where function

(array([3]),)

In [170]:
a

array([67, 78, 89, 23, 34, 45])

In [163]:
# multiple values
a[[0,3,5]]  # index

array([67, 23, 45])

In [164]:
a

array([67, 78, 89, 23, 34, 45])

In [169]:
# colon method, continous indexing

In [171]:
a[1:5]   # n-1=4

array([78, 89, 23, 34])

In [167]:
a[1:6]  # n-1=lastindex   n-1=5

array([78, 89, 23, 34, 45])

In [168]:
a[0:4]   # n-1=3

array([67, 78, 89, 23])

In [5]:
# Multi dimensional array
data=np.array([[34,45,6],[56,67,88],[89,90,99]])

In [3]:
data

array([[34, 45,  6],
       [56, 67, 88],
       [89, 90, 99]])

In [5]:
# syntax is variablename[rowindexnumber,columnindexnumber]
data[0,0]

34

In [11]:
data[0:3,1:2]    # n-1=lastindex

array([[45],
       [67],
       [90]])

In [12]:
data

array([[34, 45,  6],
       [56, 67, 88],
       [89, 90, 99]])

In [15]:
data[1:3,2:3]

array([[88],
       [99]])

In [18]:
data[0:1,1:3]

array([[45,  6]])

In [21]:
data[1:3,0:1]

array([[56],
       [89]])

In [24]:
data[1:2,0:3]

array([[56, 67, 88]])

In [25]:
data[1:2]

array([[56, 67, 88]])

In [26]:
data[1:2,0:]

array([[56, 67, 88]])

In [27]:
data[1:2,:3]

array([[56, 67, 88]])

In [28]:
data[1:2,:]

array([[56, 67, 88]])

In [29]:
data

array([[34, 45,  6],
       [56, 67, 88],
       [89, 90, 99]])

In [40]:
data.diagonal()

array([34, 67, 99])

In [43]:
np.fliplr(data).diagonal()

array([ 6, 67, 89])

In [31]:
data[[0,1,2],[0,1,2]]

array([34, 67, 99])

In [35]:
data[0:2,0:2]

array([[34, 45],
       [56, 67]])

In [37]:
data[1:3,2:3]

array([[88],
       [99]])

In [44]:
data

array([[34, 45,  6],
       [56, 67, 88],
       [89, 90, 99]])

In [47]:
b=np.arange(2,20).reshape(2,9)

In [48]:
b

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [4]:
data

array([[34, 45,  6],
       [56, 67, 88],
       [89, 90, 99]])

In [5]:
# conditional
data>65

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [6]:
data[data>65]   # values will be the outcome

array([67, 88, 89, 90, 99])

In [8]:
data

array([[34, 45,  6],
       [56, 67, 88],
       [89, 90, 99]])

In [7]:
data[data<45]

array([34,  6])

In [9]:
# Numpy operations

In [10]:
arr1=np.random.randint(4,20,(2,2))
arr2=np.random.randint(4,20,(2,2))

In [11]:
arr1

array([[12,  5],
       [ 5,  5]])

In [12]:
arr2

array([[11,  6],
       [12,  9]])

In [14]:
# concatenate function/combining
np.concatenate([arr1,arr2])  # bydefault axis=0, row

array([[12,  5],
       [ 5,  5],
       [11,  6],
       [12,  9]])

In [15]:
np.concatenate([arr1,arr2],axis=1)  # axis =1 for column

array([[12,  5, 11,  6],
       [ 5,  5, 12,  9]])

In [17]:
np.arange(4,20).reshape(4,4)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
np.array([[23,56,78],[45,56,67],[89,90,99]])

array([[23, 56, 78],
       [45, 56, 67],
       [89, 90, 99]])

In [20]:
print(arr1)
print(arr2)

[[12  5]
 [ 5  5]]
[[11  6]
 [12  9]]


In [21]:
# add function
np.add(arr1,arr2)

array([[23, 11],
       [17, 14]])

In [22]:
# subtract function
np.subtract(arr1,arr2)

array([[ 1, -1],
       [-7, -4]])

In [23]:
# Multiply function
np.multiply(arr1,arr2)

array([[132,  30],
       [ 60,  45]])

In [25]:
print(arr1)
print(arr2)

[[12  5]
 [ 5  5]]
[[11  6]
 [12  9]]


In [26]:
# Matrix multiplication, matmul function
np.matmul(arr1,arr2)
# 12*11+5*12    12*6+5*9 
# 5*11+5*12      5*6+5*9

array([[192, 117],
       [115,  75]])

In [27]:
# divide function
np.divide(arr1,arr2)

array([[1.09090909, 0.83333333],
       [0.41666667, 0.55555556]])

In [28]:
print(arr1)

[[12  5]
 [ 5  5]]


In [29]:
# sqrt function
np.sqrt(arr1)

array([[3.46410162, 2.23606798],
       [2.23606798, 2.23606798]])

In [30]:
# log function
np.log(arr1)

array([[2.48490665, 1.60943791],
       [1.60943791, 1.60943791]])

In [31]:
# sum function

In [35]:
print(arr1)

[[12  5]
 [ 5  5]]


In [34]:
np.sum(arr1)

27

In [37]:
np.sum(arr1,axis=0)  # row

array([17, 10])

In [39]:
np.sum(arr1,axis=1)  # column

array([17, 10])

In [41]:
print(arr2)

[[11  6]
 [12  9]]


In [43]:
np.sum(arr2,axis=1)

array([17, 21])

In [45]:
print(arr1)

[[12  5]
 [ 5  5]]


In [46]:
# mean function, average
np.mean(arr1)

6.75

In [47]:
np.mean(arr1,axis=0)

array([8.5, 5. ])

In [49]:
print(arr2)

[[11  6]
 [12  9]]


In [48]:
np.mean(arr2,axis=1)

array([ 8.5, 10.5])

### Pandas(Python Data Analysis library)

In [3]:
import pandas as pd

In [6]:
data

array([[34, 45,  6],
       [56, 67, 88],
       [89, 90, 99]])

In [7]:
# DataFrame function
pd.DataFrame(data)   # default indexes

0   1   2
0  34  45   6
1  56  67  88
2  89  90  99

In [9]:
df=pd.DataFrame(data,index=['A','B','C'],columns=['Marks1','Marks2','Marks3'])

In [10]:
df

Marks1  Marks2  Marks3
A      34      45       6
B      56      67      88
C      89      90      99

In [11]:
df1=pd.DataFrame({'Company':['GOOG','MSFT','FB','MSFT','GOOG'],
              'Employee':['Sravan','Pavan','Shiva','Chakri','Sirisha'],
              'Salary':[56000,67000,78000,89000,76000]})
df1

Company Employee  Salary
0    GOOG   Sravan   56000
1    MSFT    Pavan   67000
2      FB    Shiva   78000
3    MSFT   Chakri   89000
4    GOOG  Sirisha   76000

In [12]:
# slicing concept
# loc, iloc methods

In [13]:
# loc - index location name
# iloc - index location number

In [14]:
df1

Company Employee  Salary
0    GOOG   Sravan   56000
1    MSFT    Pavan   67000
2      FB    Shiva   78000
3    MSFT   Chakri   89000
4    GOOG  Sirisha   76000

In [15]:
# loc
# syntax is variablename.loc[rowindexname,columnindexname]
df1.loc[[1],['Company']]

Company
1    MSFT

In [16]:
df1.loc[[3,4],['Company','Employee','Salary']]

Company Employee  Salary
3    MSFT   Chakri   89000
4    GOOG  Sirisha   76000

In [17]:
df1.loc[[3,4]]

Company Employee  Salary
3    MSFT   Chakri   89000
4    GOOG  Sirisha   76000

In [18]:
df1.loc[[3,4],'Company':'Salary']

Company Employee  Salary
3    MSFT   Chakri   89000
4    GOOG  Sirisha   76000

In [19]:
df1

Company Employee  Salary
0    GOOG   Sravan   56000
1    MSFT    Pavan   67000
2      FB    Shiva   78000
3    MSFT   Chakri   89000
4    GOOG  Sirisha   76000

In [20]:
# iloc 
# syntax variablename.iloc[rowindexnumber,columnindexnumber]

In [21]:
df1.iloc[1,0]

'MSFT'

In [22]:
df1.iloc[3:5,0:3]

Company Employee  Salary
3    MSFT   Chakri   89000
4    GOOG  Sirisha   76000

In [23]:
df1

Company Employee  Salary
0    GOOG   Sravan   56000
1    MSFT    Pavan   67000
2      FB    Shiva   78000
3    MSFT   Chakri   89000
4    GOOG  Sirisha   76000

In [ ]:
# Missing values/null values , NaN-Not a Number

In [24]:
df2=pd.DataFrame({'Company':['GOOG',np.nan,'FB','MSFT','GOOG'],
              'Employee':['Sravan','Pavan','Shiva','Chakri','Sirisha'],
              'Salary':[56000,np.nan,78000,np.nan,76000]})

In [25]:
df2

Company Employee   Salary
0    GOOG   Sravan  56000.0
1     NaN    Pavan      NaN
2      FB    Shiva  78000.0
3    MSFT   Chakri      NaN
4    GOOG  Sirisha  76000.0

In [26]:
# dropna function

In [28]:
df2.dropna()  # axis=0  row

Company Employee   Salary
0    GOOG   Sravan  56000.0
2      FB    Shiva  78000.0
4    GOOG  Sirisha  76000.0

In [29]:
df2

Company Employee   Salary
0    GOOG   Sravan  56000.0
1     NaN    Pavan      NaN
2      FB    Shiva  78000.0
3    MSFT   Chakri      NaN
4    GOOG  Sirisha  76000.0

In [30]:
df2.dropna(axis=1)  # axis =1 column

Employee
0   Sravan
1    Pavan
2    Shiva
3   Chakri
4  Sirisha

In [33]:
# fillna function
df2.fillna(0)

Company Employee   Salary
0    GOOG   Sravan  56000.0
1       0    Pavan      0.0
2      FB    Shiva  78000.0
3    MSFT   Chakri      0.0
4    GOOG  Sirisha  76000.0

In [35]:
df2['Company']

0    GOOG
1     NaN
2      FB
3    MSFT
4    GOOG
Name: Company, dtype: object

In [37]:
df2['Company'].fillna('TCS')

0    GOOG
1     TCS
2      FB
3    MSFT
4    GOOG
Name: Company, dtype: object

In [38]:
df2['Salary']

0    56000.0
1        NaN
2    78000.0
3        NaN
4    76000.0
Name: Salary, dtype: float64

In [39]:
df2['Salary'].fillna(67000)

0    56000.0
1    67000.0
2    78000.0
3    67000.0
4    76000.0
Name: Salary, dtype: float64

In [44]:
df2.loc[1,'Salary']=79000

In [45]:
df2

Company Employee   Salary
0    GOOG   Sravan  56000.0
1     NaN    Pavan  79000.0
2      FB    Shiva  78000.0
3    MSFT   Chakri      NaN
4    GOOG  Sirisha  76000.0

In [47]:
df2.loc[[1,3],'Salary']=[80000,90000]

In [48]:
df2

Company Employee   Salary
0    GOOG   Sravan  56000.0
1     NaN    Pavan  80000.0
2      FB    Shiva  78000.0
3    MSFT   Chakri  90000.0
4    GOOG  Sirisha  76000.0

In [49]:
df1

Company Employee  Salary
0    GOOG   Sravan   56000
1    MSFT    Pavan   67000
2      FB    Shiva   78000
3    MSFT   Chakri   89000
4    GOOG  Sirisha   76000

In [50]:
#groupby function
# grouping the rows together

In [52]:
comp=df1.groupby('Company')

In [54]:
comp.groups  # to display which are being grouped

{'FB': [2], 'GOOG': [0, 4], 'MSFT': [1, 3]}

In [55]:
comp.get_group('MSFT')  # to view particular group data

Company Employee  Salary
1    MSFT    Pavan   67000
3    MSFT   Chakri   89000

In [59]:
comp.get_group('GOOG')[['Employee','Salary']]

Employee  Salary
0   Sravan   56000
4  Sirisha   76000

In [67]:
comp.mean()

Salary
Company         
FB       78000.0
GOOG     66000.0
MSFT     78000.0

In [69]:
comp.get_group('GOOG')['Salary'].mean()

66000.0

In [70]:
# Data Import and export

In [71]:
# Data import
# syntax is pd.read_excel("Path location")

In [73]:
data=pd.read_excel("/home/shyam/Documents/datasets/university.xlsx")  # linux
# windows    C:\\Users\\laptopname\\Documents\\sample.xlsx

In [75]:
data

University   SAT  Top10  Accept  SFRatio  \
0                      Harvard University  1310     89      22       13   
1      California Institute of Technology  1415    100      25        6   
2   Massachusetts Institute of Technology  1260     62      59        9   
3                     Stanford University  1310     76      24       12   
4                    Princeton University  1280     83      33       13   
..                                    ...   ...    ...     ...      ...   
95                  University of Arizona  1204     85      30       20   
96                    University of Basel  1307     80      22       10   
97   University of Maryland, College Park  1313     82      28       29   
98                      Dartmouth College  1231     76      18       19   
99         Technical University of Munich  1323     79      35       11   

    Expenses  GradRate  
0      22704        94  
1      63575        81  
2      25026        72  
3      31510        88  
4      21864        90  
..       ...       ...  
95     37657        82  
96     57533        84  
97     45583        91  
98     68894        95  
99     40266        90  

[100 rows x 7 columns]

In [77]:
# text file/csv(comma seperated values)
car=pd.read_csv("/home/shyam/Documents/datasets/cars.csv")

In [78]:
car

car_model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [80]:
df1

Company Employee  Salary
0    GOOG   Sravan   56000
1    MSFT    Pavan   67000
2      FB    Shiva   78000
3    MSFT   Chakri   89000
4    GOOG  Sirisha   76000

In [81]:
# exporting the data

In [83]:
# syntax is variablename.to_excel("Path location")
df1.to_excel("/home/shyam/Documents/company.xlsx",index=False)

In [84]:
df1.to_csv("/home/shyam/Documents/sample.csv",index=False)

In [85]:
# Pandas operations

In [86]:
# head function, bydefault first five records to display
car.head()

car_model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [88]:
car.head(7)

car_model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
5            Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
6         Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2  
5     1  
6     4

In [89]:
# tail function, bydefault last five records to display
car.tail()

car_model   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4   

    carb  
27     2  
28     4  
29     6  
30     8  
31     2

In [90]:
car.tail(2)

car_model   mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
30  Maserati Bora  15.0    8  301.0  335  3.54  3.57  14.6   0   1     5     8
31     Volvo 142E  21.4    4  121.0  109  4.11  2.78  18.6   1   1     4     2

In [93]:
car.loc[10:15,['car_model','mpg']]

car_model   mpg
10            Merc 280C  17.8
11           Merc 450SE  16.4
12           Merc 450SL  17.3
13          Merc 450SLC  15.2
14   Cadillac Fleetwood  10.4
15  Lincoln Continental  10.4

In [94]:
car.columns

Index(['car_model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [95]:
car.index

RangeIndex(start=0, stop=32, step=1)

In [96]:
car.shape

(32, 12)