## COPYING/SORTING/RESHAPING

In [1]:
import numpy as np

In [3]:
array = np.random.randint(1,20,15)
array

array([17, 19, 19,  3,  3, 19,  3, 14, 12, 17, 16, 13,  6,  2, 10])

In [4]:
a = np.random.randint(1,20,(2,4))
a

array([[19,  5,  8,  5],
       [16,  6,  3, 11]])

### Copy

Return an array copy of the given object.


In [6]:
array

array([17, 19, 19,  3,  3, 19,  3, 14, 12, 17, 16, 13,  6,  2, 10])

In [7]:
array1 = array
array1

array([17, 19, 19,  3,  3, 19,  3, 14, 12, 17, 16, 13,  6,  2, 10])

In [8]:
array1 = np.copy(array)
array1

array([17, 19, 19,  3,  3, 19,  3, 14, 12, 17, 16, 13,  6,  2, 10])

### Sort

Return a sorted copy of an array.

In [10]:
np.sort(array)

array([ 2,  3,  3,  3,  6, 10, 12, 13, 14, 16, 17, 17, 19, 19, 19])

In [11]:
array.sort()

In [12]:
array

array([ 2,  3,  3,  3,  6, 10, 12, 13, 14, 16, 17, 17, 19, 19, 19])

### Transpose

Transposes arr (rows become columns and
vice versa

In [13]:
matrix = np.random.randint(0,15,(5,3))
matrix

array([[14,  8, 14],
       [12,  1, 13],
       [11, 11, 10],
       [ 8,  4,  9],
       [12, 11,  4]])

In [14]:
matrix.T

array([[14, 12, 11,  8, 12],
       [ 8,  1, 11,  4, 11],
       [14, 13, 10,  9,  4]])

### Reshape

Returns an array containing the same data with a new shape.

In [ ]:
array

In [ ]:
array.ndim

In [ ]:
array.reshape((3,5))

In [ ]:
array.reshape((5,3))

## ADDING/REMOVING ELEMENTS

### append

Append values to the end of an array.

In [29]:
array

array([ 2,  3,  3,  3,  6, 10, 12, 13, 14, 16, 17, 17, 19, 19, 19])

In [34]:
array = np.append(array,20)

In [35]:
array

array([ 2,  3,  3,  3,  6, 10, 12, 13, 14, 16, 17, 17, 19, 19, 19, 20])

### Insert

Insert values along the given axis before the given indices.

In [45]:
array = np.insert(array,2,[25,34,56])

In [46]:
array

array([ 2,  3, 25, 34, 56, 25,  3,  3,  6, 10, 12, 13, 14, 16, 17, 17, 19,
       19, 19, 20])

### Delete

Return a new array with sub-arrays along an axis deleted.

In [47]:
array

array([ 2,  3, 25, 34, 56, 25,  3,  3,  6, 10, 12, 13, 14, 16, 17, 17, 19,
       19, 19, 20])

In [ ]:
np.delete(array,2)

In [48]:
np.delete(array,[2,5,1])

array([ 2, 34, 56,  3,  3,  6, 10, 12, 13, 14, 16, 17, 17, 19, 19, 19, 20])

In [49]:
matrix

array([[14,  8, 14],
       [12,  1, 13],
       [11, 11, 10],
       [ 8,  4,  9],
       [12, 11,  4]])

In [51]:
np.delete(matrix,2,axis=1) # Deletes row on index 3 of arr

array([[14,  8],
       [12,  1],
       [11, 11],
       [ 8,  4],
       [12, 11]])

In [52]:
matrix

array([[14,  8, 14],
       [12,  1, 13],
       [11, 11, 10],
       [ 8,  4,  9],
       [12, 11,  4]])

In [53]:
np.delete(matrix,2,axis=1) # Deletes column on index 4 of arr

array([[14,  8],
       [12,  1],
       [11, 11],
       [ 8,  4],
       [12, 11]])

## Concatenate and Splitting

In [54]:
arr1 = np.array([[5,6,9]])
arr2 = np.array([[1,2,3]])

### Concatenate

Join a sequence of arrays along an existing axis.

In [56]:
np.concatenate((arr1,arr2),axis=0) # Adds arr2 as rows to the end of arr1

array([[5, 6, 9],
       [1, 2, 3]])

In [57]:
np.concatenate((arr1,arr2),axis=1) # Adds arr2 as rows to the end of arr1

array([[5, 6, 9, 1, 2, 3]])

In [58]:
arr1 = np.random.randint(1,4,(2,2))
arr1

array([[1, 1],
       [1, 2]])

In [59]:
arr2 = np.random.randint(1,4,(2,2))
arr2

array([[3, 1],
       [2, 1]])

In [60]:
np.concatenate((arr1,arr2),axis=0) # Adds arr2 as columns to end of arr1

array([[1, 1],
       [1, 2],
       [3, 1],
       [2, 1]])

In [61]:
np.concatenate((arr1,arr2),axis=1) # Adds arr2 as columns to end of arr1

array([[1, 1, 3, 1],
       [1, 2, 2, 1]])

### Split

In [62]:
matrix

array([[14,  8, 14],
       [12,  1, 13],
       [11, 11, 10],
       [ 8,  4,  9],
       [12, 11,  4]])

In [67]:
np.split(matrix,5,axis=0)

[array([[14,  8, 14]]),
 array([[12,  1, 13]]),
 array([[11, 11, 10]]),
 array([[8, 4, 9]]),
 array([[12, 11,  4]])]

In [65]:
np.split(matrix,3,axis=1)

[array([[14],
        [12],
        [11],
        [ 8],
        [12]]),
 array([[ 8],
        [ 1],
        [11],
        [ 4],
        [11]]),
 array([[14],
        [13],
        [10],
        [ 9],
        [ 4]])]

## SCALAR MATH

In [68]:
array

array([ 2,  3, 25, 34, 56, 25,  3,  3,  6, 10, 12, 13, 14, 16, 17, 17, 19,
       19, 19, 20])

### add

Add arguments element-wise.

In [69]:
np.add(array,2)
#array + 2

array([ 4,  5, 27, 36, 58, 27,  5,  5,  8, 12, 14, 15, 16, 18, 19, 19, 21,
       21, 21, 22])

### Substract

Subtract arguments, element-wise.

In [71]:
np.subtract(array,3)

array([-1,  0, 22, 31, 53, 22,  0,  0,  3,  7,  9, 10, 11, 13, 14, 14, 16,
       16, 16, 17])

### Multiply

Multiply arguments element-wise.

In [72]:
np.multiply(array,2)

array([  4,   6,  50,  68, 112,  50,   6,   6,  12,  20,  24,  26,  28,
        32,  34,  34,  38,  38,  38,  40])

### Divide

Returns a true division of the inputs, element-wise.

In [73]:
array

array([ 2,  3, 25, 34, 56, 25,  3,  3,  6, 10, 12, 13, 14, 16, 17, 17, 19,
       19, 19, 20])

In [74]:
np.divide(array,2)

array([ 1. ,  1.5, 12.5, 17. , 28. , 12.5,  1.5,  1.5,  3. ,  5. ,  6. ,
        6.5,  7. ,  8. ,  8.5,  8.5,  9.5,  9.5,  9.5, 10. ])

### Power

First array elements raised to powers from second array, element-wise.

In [ ]:
array

In [78]:
np.power(array,2)

array([   4,    9,  625, 1156, 3136,  625,    9,    9,   36,  100,  144,
        169,  196,  256,  289,  289,  361,  361,  361,  400], dtype=int32)

## VECTOR MATH


In [79]:
arr1

array([[1, 1],
       [1, 2]])

In [80]:
arr2

array([[3, 1],
       [2, 1]])

In [81]:
np.add(arr1,arr2)

array([[4, 2],
       [3, 3]])

In [82]:
arr1 + arr2

array([[4, 2],
       [3, 3]])

In [83]:
np.subtract(arr1,arr2)

array([[-2,  0],
       [-1,  1]])

In [84]:
np.multiply(arr1,arr2)

array([[3, 1],
       [2, 2]])

In [85]:
np.divide(arr1,arr2)

array([[0.33333333, 1.        ],
       [0.5       , 2.        ]])

In [87]:
print(arr1)
print(arr2)

[[1 1]
 [1 2]]
[[3 1]
 [2 1]]


In [88]:
np.power(arr1,arr2)

array([[1, 1],
       [1, 2]], dtype=int32)

In [89]:
np.sqrt(arr1)

array([[1.        , 1.        ],
       [1.        , 1.41421356]])

In [90]:
np.sin(arr1)

array([[0.84147098, 0.84147098],
       [0.84147098, 0.90929743]])

In [91]:
np.cos(arr1)

array([[ 0.54030231,  0.54030231],
       [ 0.54030231, -0.41614684]])

In [92]:
np.log(arr1)

array([[0.        , 0.        ],
       [0.        , 0.69314718]])

### Ceil

Roundup to the next greatest integer

In [93]:
arr = np.array([2.5,3.9,4,1.2])
arr

array([2.5, 3.9, 4. , 1.2])

In [94]:
np.ceil(arr)

array([3., 4., 4., 2.])

### floor

Roundup to next least integer

In [95]:
arr

array([2.5, 3.9, 4. , 1.2])

In [96]:
np.floor(arr)

array([2., 3., 4., 1.])

### Round

Round an array to the given number of decimals.

In [97]:
np.round(arr,2)

array([2.5, 3.9, 4. , 1.2])

## Statistics

In [98]:
arr1

array([[1, 1],
       [1, 2]])

In [100]:
5/4

1.25

In [99]:
np.mean(arr1)

1.25

In [101]:
np.mean(arr1,axis=1) #  Column wise mean

array([1. , 1.5])

In [102]:
np.mean(arr1,axis=0) # Row wise mean

array([1. , 1.5])

In [103]:
arr1.sum()

5

In [104]:
arr1.min()

1

In [105]:
arr1.max()

2

In [106]:
np.var(arr1)

0.1875

In [107]:
np.std(arr1)

0.4330127018922193

In [108]:
np.std(arr1,axis=0) # Row wise std

array([0. , 0.5])

In [109]:
np.std(arr1,axis=1) # Column wise std

array([0. , 0.5])

### Dot

Dot product of two arrays.

In [110]:
arr1

array([[1, 1],
       [1, 2]])

In [111]:
arr2

array([[3, 1],
       [2, 1]])

In [114]:
arr1.dot(arr2)

array([[5, 2],
       [7, 3]])

In [115]:
arr1 * arr2

array([[3, 1],
       [2, 2]])

### comparision Operators

>,<,>=,<=,==,!=

In [116]:
matrix

array([[14,  8, 14],
       [12,  1, 13],
       [11, 11, 10],
       [ 8,  4,  9],
       [12, 11,  4]])

In [117]:
matrix >= 5

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [118]:
matrix[matrix > 5]

array([14,  8, 14, 12, 13, 11, 11, 10,  8,  9, 12, 11])

In [119]:
matrix[matrix==6]

array([], dtype=int32)

In [120]:
matrix[matrix!=5]

array([14,  8, 14, 12,  1, 13, 11, 11, 10,  8,  4,  9, 12, 11,  4])

In [121]:
matrix[(matrix>5) & (matrix < 10)]

array([8, 8, 9])

In [122]:
matrix[(matrix>5) and (matrix < 10)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [123]:
matrix[(matrix >5) | (matrix <12 )]

array([14,  8, 14, 12,  1, 13, 11, 11, 10,  8,  4,  9, 12, 11,  4])