# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.



In [3]:
import numpy as np



Numpy has many built-in functions and capabilities:vectors,arrays,matrices, and number generation.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).



## Creating NumPy Arrays

you can create an array from a regular Python list or tuple using the `array` function.






**`syntax: np.array(object, dtype=None,ndmin=0)`**

#### Create an Array from List

In [1]:
list1 = [1,2,3,4,5]

In [4]:
a = np.array(list1)

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
type(a)

numpy.ndarray

In [5]:
print(a)

print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
np.array([1,2,0,4,5],dtype = str)



array(['1', '2', '0', '4', '5'], dtype='<U1')

In [15]:
array(1,2,3,4,5)

NameError: name 'array' is not defined

In [16]:
# Create an 1d -array from python list
List1 = [2,6,3,4]

array= np.array(List1) 
array 

array([2, 6, 3, 4])

In [17]:
type(List1)

list

In [18]:
type(array)

numpy.ndarray

In [19]:
#create a matrix with 2-rows and 3-columns
List2 = [[2,3,6],[5,4,8],[1,2,3,4]]

In [20]:
# Create an array from above matrix

array = np.array(List2)
array # Two dimensional array

array([[2, 3, 6],
       [5, 4, 8]])

In [23]:
#create a matrix with 2-rows and 3-columns
List2 = [[2,3,6],[5,4,8],[1,2,3,4]]

list2

NameError: name 'list2' is not defined

#### Create an array from tuple

In [24]:
# tuple
Tuple = (2,3,6,9)

array = np.array(Tuple)

In [25]:
array

array([2, 3, 6, 9])

In [26]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])

In [27]:
type(my_array)

numpy.ndarray

In [ ]:
my_array

In [28]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10],dtype= complex)

In [29]:
my_array

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j,
        8.+0.j,  9.+0.j, 10.+0.j])

In [35]:
my_array1  = np.array([1,2,3,4,5,6,7,8,9,10],ndmin=2)

In [33]:
my_array1  = np.array([1,2,3,4,5,6,7,8,9,10])

my_array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
my_array1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

#### Array of integers, floats and complex Numbers

In [36]:
A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [37]:
A = np.array([[1.1, 2, 3], [3, 4, 5]],) # Array of floats
print(A)


[[1.1 2.  3. ]
 [3.  4.  5. ]]


In [ ]:
# Upcasting
A = np.array([1,2,3.2])
A

# The degree of integer is lower than the float

In [ ]:
A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)

In [ ]:
A = np.array([[1, 2, 3], [3, 4, 5]], dtype = int) # Array of complex numbers
print(A)

In [ ]:
A = np.array([[1, 2, 3], [3, 4, 5]], dtype = str) # Array of complex numbers
print(A)

In [ ]:
A = np.array([[1, 2, 3], [3, 4, 5]], dtype = float) # Array of complex numbers
print(A)

In [ ]:
A = np.array([[1, 2, 3], [3, 4, 0]], dtype = bool) # Array of complex numbers
print(A)

In [38]:
# Minimum two dimensions
np.array([2,3,6,9],ndmin=2)

array([[2, 3, 6, 9]])

In [39]:
np.array([2,3,6,9],ndmin=3)

array([[[2, 3, 6, 9]]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

- np.arange()
- np.linspace()
- np.zero()
- np.ones()
- np.eye()
- np.full()
- np.random.rand()
- np.random.randn()
- np.random.randint()

### arange

**syntax**

   **`np.arange([start,] stop[, step,], dtype=None)`**

Return evenly spaced values within a given interval.

In [40]:
array = np.arange(0,10) # create an array from 0 to 10 (10 is exclusive)

In [41]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
array = np.arange(0,10,2)

In [43]:
array

array([0, 2, 4, 6, 8])

In [47]:
np.arange(0,101,25)

array([  0,  25,  50,  75, 100])

In [50]:
np.arange(100,200,2,dtype= complex)

array([100.+0.j, 102.+0.j, 104.+0.j, 106.+0.j, 108.+0.j, 110.+0.j,
       112.+0.j, 114.+0.j, 116.+0.j, 118.+0.j, 120.+0.j, 122.+0.j,
       124.+0.j, 126.+0.j, 128.+0.j, 130.+0.j, 132.+0.j, 134.+0.j,
       136.+0.j, 138.+0.j, 140.+0.j, 142.+0.j, 144.+0.j, 146.+0.j,
       148.+0.j, 150.+0.j, 152.+0.j, 154.+0.j, 156.+0.j, 158.+0.j,
       160.+0.j, 162.+0.j, 164.+0.j, 166.+0.j, 168.+0.j, 170.+0.j,
       172.+0.j, 174.+0.j, 176.+0.j, 178.+0.j, 180.+0.j, 182.+0.j,
       184.+0.j, 186.+0.j, 188.+0.j, 190.+0.j, 192.+0.j, 194.+0.j,
       196.+0.j, 198.+0.j])

### zeros

Return a new array of given shape and type, filled with zeros.

**Syntax**

 **`np.zeros(shape, dtype=float, order='C')`**
   
- Shape of the new array, e.g., `(7, 3)` or `5`
- The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`

In [51]:
# Generate an array of zeros of shape 3
Zeros = np.zeros(4)
Zeros

array([0., 0., 0., 0.])

In [55]:
Zeros = np.zeros((4,5),dtype=complex,order = 'F')
Zeros

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [59]:
Zeros = np.zeros((4,5),dtype=complex,order = 'C')
Zeros

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [60]:
ones = np.ones((4,5))

In [68]:
var = np.ones((4,5))

In [69]:
var

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
np.full((5,9),1.1)

array([[1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1],
       [1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1],
       [1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1],
       [1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1],
       [1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1]])

In [74]:
# Generate an array of Zeros of shape 5x5
ram=np.zeros((5,5))
ram


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [77]:
# Generate an array of ones of shape
sekhar=np.ones((3))
sekhar

array([1., 1., 1.])

In [80]:
# Generate an array of ones of shape of 5X5
ones=np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
a = np.full((3,3),2+5j)
a
              #Generate an array of complex numbers 2+5j of shape of 3x3

array([[2.+5.j, 2.+5.j, 2.+5.j],
       [2.+5.j, 2.+5.j, 2.+5.j],
       [2.+5.j, 2.+5.j, 2.+5.j]])

In [85]:
# Generate an array of multiples of 3 upto 100
a = np.arange(0,100,3)
a


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

### linspace
Return evenly spaced numbers over a specified interval.

**syntax**

**`np.linspace(start, stop, num=50,dtype=None)`**



In [88]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [89]:

L = np.linspace(0,10)
L

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [90]:
# Generate an array 100 elements between 2 to 5
L = np.linspace(2,5,100)
L

array([2.        , 2.03030303, 2.06060606, 2.09090909, 2.12121212,
       2.15151515, 2.18181818, 2.21212121, 2.24242424, 2.27272727,
       2.3030303 , 2.33333333, 2.36363636, 2.39393939, 2.42424242,
       2.45454545, 2.48484848, 2.51515152, 2.54545455, 2.57575758,
       2.60606061, 2.63636364, 2.66666667, 2.6969697 , 2.72727273,
       2.75757576, 2.78787879, 2.81818182, 2.84848485, 2.87878788,
       2.90909091, 2.93939394, 2.96969697, 3.        , 3.03030303,
       3.06060606, 3.09090909, 3.12121212, 3.15151515, 3.18181818,
       3.21212121, 3.24242424, 3.27272727, 3.3030303 , 3.33333333,
       3.36363636, 3.39393939, 3.42424242, 3.45454545, 3.48484848,
       3.51515152, 3.54545455, 3.57575758, 3.60606061, 3.63636364,
       3.66666667, 3.6969697 , 3.72727273, 3.75757576, 3.78787879,
       3.81818182, 3.84848485, 3.87878788, 3.90909091, 3.93939394,
       3.96969697, 4.        , 4.03030303, 4.06060606, 4.09090909,
       4.12121212, 4.15151515, 4.18181818, 4.21212121, 4.24242

In [ ]:
np.linspace(0,2,100)

In [95]:
np.linspace(1,10,5,endpoint=True,retstep=True) 

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [94]:
np.linspace(1,10,5,endpoint=False,retstep=True)

(array([1. , 2.8, 4.6, 6.4, 8.2]), 1.8)

In [93]:
np.linspace(1,10,5,retstep=True) # To know the step size .it will return step size

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

## eye

   
Creates an identity matrix

**syntax**

**`np.eye(N, M=None,dtype=<class 'float'>)`**
   
- N : int
  Number of rows in the output.
- M : int, optional
  Number of columns in the output. If None, defaults to `N`.
- dtype : data-type, optional
  Data-type of the returned array.


In [96]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [97]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8)

## ones

Returns an array of all ones.

**`np.ones(shape, dtype=None, order='C')`**

In [ ]:
a = np.ones((2,2))

In [ ]:
a

## constant array
Return a new array of given shape and type, filled with `fill_value`.

**`np.full(shape, fill_value, dtype=None, order='C')`**

In [ ]:
#Create a 3x3 array with constant value 7

np.full((3,3),7.5)

## Random 

Numpy also has lots of ways to create random number arrays:

### 1. rand

Random values in a given shape.

Create an array of the given shape and populate it with
random samples from a **uniform distribution**
over ``[0, 1)``.

**syntax**

   `rand(d0, d1, ..., dn)`
   
   - d0, d1, ..., dn : int, optional
    The dimensions of the returned array, should all be positive.


In [99]:
# Generate an array of 5 random numbers from a uniform distribution
U = np.random.rand(5)
U

array([0.08234164, 0.54733976, 0.98362934, 0.65957692, 0.01529799])

In [101]:
# Generate an array of 5,2 random numbers from a uniform distribution

U = np.random.rand(5,2)
U

array([[0.74858639, 0.75844783],
       [0.02878535, 0.352704  ],
       [0.78074171, 0.33902432],
       [0.75110944, 0.25700794],
       [0.97740822, 0.18916394]])

### 2.randn

Return a sample (or samples) from the **standard normal distribution**.

**syntax**
  
  `randn(d0, d1, ..., dn)`

In [102]:
# Generate an array of 5 random numbers from a standard normal distribution

N = np.random.randn(5)
N

array([-0.19554266,  0.29708175, -1.32347899,  0.92358998,  0.24754695])

In [103]:
# Generate an array of 5,2 random numbers from a standard normal distribution

N = np.random.randn(5,2)
N

array([[-0.4821863 , -0.02014836],
       [-0.09100086,  0.43608728],
       [-0.49862662, -1.31634478],
       [ 0.29165673, -1.20021595],
       [ 0.46972327, -0.1562481 ]])

### 3. randint
Return random integers from `low` (inclusive) to `high` (exclusive).

**syntax**

`randint(low, high=None, size=None)`


In [104]:
import numpy as np

In [111]:
np.random.randint(50,100,size = (5,5))

array([[94, 89, 77, 90, 77],
       [95, 76, 87, 55, 78],
       [50, 80, 63, 60, 52],
       [92, 94, 61, 73, 70],
       [79, 98, 52, 82, 64]])

In [112]:
a = np.arange(0,36)

In [113]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [115]:
a = a.reshape(3,12)

a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [116]:
a = a.reshape(5,5)

ValueError: cannot reshape array of size 36 into shape (5,5)

In [117]:
a.size

36

In [118]:
a.shape

(3, 12)

In [119]:
a.ndim

2

In [120]:
a.dtype

dtype('int32')

## Array Attributes and Method


Let's discuss some useful attributes of an array like the size, shape, memory consumption, and data types.

-  array.size
-  array.shape
-  array.dtype
-  array.ndim
-  array.reshape()
-  array.astype()
-  array.asarray()

### 1. ndarray.shape 

This array attribute returns a tuple consisting of `array dimensions`. It can also be used to resize the array.

In [ ]:
arr1 = np.array([[3,4],[8,9]])
arr2 = np.array([[3,4,5],[9,7,8]])
arr3 = np.array([[3,6,8,7],[5,9,8,7],[2,5,3,7]])

In [ ]:
arr1.shape

In [ ]:
arr2.shape

In [ ]:
arr3.shape

In [ ]:
#Resize arr3 by using shape attribute
arr3.shape = (4,3)

In [ ]:
arr3

## 2. Reshape( )
Returns an array containing the same data with a new shape.

In [ ]:
arr4 = np.arange(0,10).reshape(2,5)

In [ ]:
arr4

In [ ]:
a = np.random.randint(1,20,10)
a

In [ ]:
len(a)

In [ ]:
a.reshape((-1,5)) # By default it will understand what will be suitable row dimension

In [ ]:
a.reshape((5,-1)) # By defaut it will understand what will be suitable column dimension

## 3. ndarray.ndim

This array attribute returns the `number of array dimensions`.

In [ ]:
# One dimensional array

onedm = np.array([2,3,6,9])
onedm.ndim

In [ ]:
# Two dimensional array
twodm = np.array([[2,5,8],[7,8,9]])

In [ ]:
twodm.ndim

In [ ]:
# Three dimensional array
threedm = np.array([[[2,3,6],[5,8,9],[9,8,7]]])

In [ ]:
threedm.ndim

## 4.ndarray.itemsize

This array attribute returns the length of each element of array in bytes.

In [ ]:
onedm.itemsize

In [ ]:
threedm.itemsize

## 5.ndarray.size

Returns the total size of the array

In [ ]:
onedm.size

In [ ]:
twodm.size

In [ ]:
threedm.size

## 6.ndarray.dtype

Returns the type of data


In [ ]:
onedm.dtype

In [ ]:
onedm.astype(float)

## 7. ndarray.astype()
a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

Copy of the array, cast to a specified type.

In [122]:
a = np.arange(0,10)

In [123]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
a.astype(complex)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

## 8 np.asarray()

Convert the input to an array.

In [126]:
# Convert a list into an array
a = [5,6,7]

np.asarray(a)

array([5, 6, 7])

In [127]:
# Convert a list into an array
a = [5,6,7]

np.array(a)

array([5, 6, 7])

In [ ]:
np.asarray(a) is a # a is a list not an array that's why it is false

In [ ]:
b = np.array(a)
b 

In [ ]:
np.asarray(b) is b # 'is' operator going to check the instance of both object is same or not

In [ ]:
np.asarray(b) is np.array(a)